### ISSUE TITLE
when set, baseUrl is being repeated for og:image 

### ISSUE THREAD

**Issue by stacykgrimes** [apostrophecms/apostrophe-open-graph#21] opened 2020-05-20 20:30 UTC
When `baseUrl` is set in `data/local.js`, the `og:image` URL being passed is listing the `baseUrl` **_twice_**, unless the `baseUrl` logic is removed (at project level) from the `apostrophe-open-graph` template

**Example from [PHS website](https://phsonline.org/for-gardeners/gardening-competitions):** 
`<meta property="og:image" content="https://phsonline.orghttps://phsonline.org/uploads/attachments/cka8btume0uwojwranll21wg2-2020-gc-1227x540-3.407.0.4297.2250.full.jpg">`

https://github.com/apostrophecms/apostrophe-open-graph/blob/124a44f29a350df016bf6a66669d8a8d5cfda160/views/view.html#L31

_PHS is a newly launched site with Apostrophe version `2.106.0` and the production server is using `Node 8`._

**Comment by abea** [comment] 2020-05-20 20:53
This is a regression caused by #19 . We should instead make it more clear that `baseUrl` is critical to this module working.

**Comment by boutell** [comment] 2020-05-21 12:32
It can actually be fixed without baseUrl, because at the time an open graph URL for an image is being built, we know the URL that was requested. Therefore we can do the math correctly.

We just have to do it carefully.

The image URL comes from uploadfs. If local storage is being used it will start with /, if not it will actually be on some CDN and should be left well alone.

So the logic *for making image URLs absolute* (for pages this is already done, don't duplicate it!) looks like:

If image-url-is-not-absolute then prepend `req.baseUrl`

True fact: `req.baseUrl` is a real thing that could benefit from documentation! In fact, here's all of what should go in that documentation:

## Accessing absolute URLs

Sometimes you must have an absolute URL, for instance for open graph, or generating an email.

If you are generating an email in a command line task, your only option is to pass the `baseUrl` global option when configuring Apostrophe. This must look like:

https://mysite.com

It must NOT contain a trailing slash, and it must NOT duplicate any `prefix` global option, which will be appended automatically where appropriate.

However, outside of a command line task, setting this option is not mandatory. Apostrophe will always respect `baseUrl` if it has been set, but will also infer the base URL from the actual request received from the browser.

During a request, you can access the following useful extra properties of `req`:

`req.baseUrl`

This is the global `baseUrl` if set, otherwise it is inferred from `req.protocol` and `req.get('Host')`, which will give the right answer in most configurations. If your frontend proxy does not pass on the original requested URL you may need to set the `baseUrl` option.

`req.baseUrlWithPrefix`

The same, but with the global `prefix` option appended. *You usually won't need this,* as Apostrophe provides the prefix for you in most situations.

`req.absoluteUrl`

The complete absolute URL of the current request, including baseUrl (as configured or inferred) and prefix (if any).

**Comment by abea** [comment] 2020-05-22 21:01
@boutell Right now the url construction is happening in the template with `apos.attachments.url()`. To do this `req.baseUrl` and image URL checking we'd need to do some server-side work. So are you suggesting we add a new `apos.openGraph` template helper method to the module to use the `attachments` method, then do a bit more logic and return the full, correct URL?

**Comment by boutell** [comment] 2020-05-26 17:35
... I guess not. My proposed fix doesn't account for the fact that a global, root baseUrl not requiring `req` is necessary in our current model of how uploadfs works, and probably should be for friendliness to adaptation to CDNs later in the lifecycle of a site, etc. It's better to document that baseUrl should always be set when apostrophe-open-graph is desired and our default local file storage is in use. (When s3 etc. are in use it's no longer relevant.)

**Comment by abea** [comment] 2020-05-26 20:04
Okay. I think #22 is ready to go then.

**Closed as completed** 2020-05-27 13:49 UTC
Labels: bug
